sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- v11
- v10
- v8
- v6
- node
before_install:
- npm install -g codecov
script:
- npm run test
after_success:
- codecov
deploy:
  provider: npm
  email: $EMAIL
  api_key:
    secure: $API_KEY
  on:
    tags: true
    branch: master
