sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- v11
- v10
- v8
- v6
- node
script:
- npm run test
deploy:
  provider: npm
  email: $EMAIL
  api_key: $API_KEY
  on:
    tags: true
    branch: master
